# https://docs.amd.com/r/en-US/ug1393-vitis-application-acceleration/xrt.ini-File

[Runtime]
runtime_log=console
verbosity=4

[Debug]
#native_xrt_trace=true
#device_trace=fine
#stall_trace=all
#aie_trace=true
#aie_profile=true
#aie_status=true

[Emulation]
#debug_mode=gui
#user_pre_sim_script=/path/to/pre_sim.tcl
#aliveness_message_interval=60

[AIE_profile_settings]
#tile_based_aie_metrics=all:heat_map
#tile_based_aie_memory_metrics=all:conflicts
#tile_based_interface_tile_metrics=
#graph_based_aie_metrics=
#graph_based_aie_memory_metrics=

[AIE_trace_settings]
#tile_based_aie_tile_metrics=all:functions
#graph_based_aie_tile_metrics=all:all:functions
#tile_based_aie_tile_metrics=all:all_stalls
#graph_based_aie_tile_metrics=all:all:all_stalls

